/* PostgreSQL connection and ORM 
*/

spring.application.name=support-ticket-api

spring.datasource.url=jdbc:postgresql://localhost:5433/support_ticket_system
spring.datasource.username=ardakarakaya
spring.datasource.password=230314

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080